# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSChatExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSCore'
  pod 'AWSConnect'
  pod 'AWSConnectParticipant'
  pod 'Starscream', '~> 4.0'

  # Pods for Chat

  target 'iOSChatExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSChatExampleUITests' do
    # Pods for testing
  end

end
