AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-connect-interactive-messages-example-lex-v2
    Description: Creates AWS Lambda function to be used as an initialization and validation
      code hook in Amazon Lex Bot (v2) for enabling interactive messages in Amazon
      Connect Chat.
    Author: Amazon Connect Messaging
    SpdxLicenseId: MIT-0
    LicenseUrl: s3://amazon-connect-interactive-message-blog-assets-lex-v2/b974f276fb24c64a763c529eb1fd9a05
    ReadmeUrl: s3://amazon-connect-interactive-message-blog-assets-lex-v2/55deff029765dcc1c4918a9573e3b6d7
    Labels:
    - connect
    - chat
    - interactive-messaging
    - contact-center
    - lambda
    - lex
    - bot
    - lex-v2
    HomePageUrl: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/samTemplates/amazon-connect-interactive-messages-example-lex-v2
    SemanticVersion: 2.0.1
    SourceCodeUrl: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/samTemplates/amazon-connect-interactive-messages-example-lex-v2
Globals:
  Function:
    Timeout: 30
Resources:
  InteractiveMessagingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://amazon-connect-interactive-message-blog-assets-lex-v2/b4a4ab219d54e6c1daf877f8ad1c43ac
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
    Metadata:
      SamResourceId: InteractiveMessagingLambdaFunction
Outputs:
  InteractiveMessagingLambdaFunction:
    Description: Interactive Messaging Lex Lambda Function ARN
    Value:
      Fn::GetAtt:
      - InteractiveMessagingLambdaFunction
      - Arn
  InteractiveMessagingFunctionIamRole:
    Description: Implicit IAM Role created for Interactive Messaging Lex Lambda Function
    Value:
      Fn::GetAtt:
      - InteractiveMessagingLambdaFunctionRole
      - Arn
